{% set name = "dtool_lookup_server" %}
{% set version = "0.18.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/dtool-lookup-server/dtool-lookup-server-{{ version }}.tar.gz
  sha256: 1aca3bf5644f41f25531ee52d109ab829a067421c5c01f3b5a64a69056179edf

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - alembic
    - dtool_ecs
    - dtool_irods
    - dtool_s3
    - dtoolcore >=3.18.0
    - flask
    - flask-cors
    - flask-jwt-extended >=4.0
    - flask-migrate
    - flask-pymongo
    - flask-sqlalchemy
    - flask-smorest
    - flask-marshmallow
    - pymongo
    - python >={{ python_min }}
    - pyyaml
    - marshmallow-sqlalchemy

test:
  imports:
    - dtool_lookup_server
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jic-dtool/dtool-lookup-server
  summary: Web API to register/lookup/search for dtool dataset metadata
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
